title: Rust for Rustaceans by Jon Gjengset
email: jon@thesquareplanet.com
description: >-
  For developers whoâ€™ve mastered the basics, this book is the next step on your
  way to professional-level programming in Rust. It covers everything you need
  to build and maintain larger code bases, write powerful and flexible
  applications and libraries, and confidently expand the scope and complexity
baseurl: ""
url: "https://rust-for-rustaceans.com"
domain: rust-for-rustaceans.com
twitter_username: jonhoo
github_username:  jonhoo

theme: minima
plugins:
  - jekyll-feed

collections:
  errata:
    sort_by: page
  testimonials:
    sort_by: weight
  features:

markdown: CommonMark
commonmark:
  options: ["SMART", "UNSAFE"]
  extensions: ["strikethrough"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
